sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 192.168.182.131
    port: 3306
    database: sky_take_out
    username: root
    password: root


spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB