sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 192.168.182.131
    port: 3306
    database: sky_take_out
    username: root
    password: root
  redis:
    host: 192.168.182.131
    port: 6379
    password: redis
    database: 0
  wechat:
    appid: 00000000
    secret: 00000000


spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB